# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
environment: dev
nodeenv: production
image:
  repository: eu.gcr.io/mmdh-dev/embou-frontend
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
autoscaler:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
disruptionbudget:
  enabled: true
ingress:
  enabled: true
  tls: true
  tlsSecret: embou-dev-tls
  basefqdn: embou.dev.digitalhub.masmovil.com
  basepath: /
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
resources:
   limits:
    cpu: 1000m
    memory: 1500Mi
   requests:
    cpu: 100m
    memory: 512Mi
livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1