# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
environment: dev
autoscaler:
  enabled: true
disruptionbudget:
  enabled: false
ingress:
  # Used to create an Ingress record.
  tls: true
  records:
    - host: embou.dev.digitalhub.masmovil.com
      path: /
resources:
   limits:
    cpu: 1000m
    memory: 1500Mi
   requests:
    cpu: 400m
    memory: 512Mi
livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
